#!/usr/bin/python3
import setup
from stateMachines import Path, get_default_state_machines

sol = "fplfrfffrffffrffprflflffffprrfffrffflfflflfplfrfrffprflflfffprflflfffprflflfplfffrffffrffflffflflfffplfrfrffprflflfffprflflfplfffrfflfffflfflflfplfrfrfffplfrfrffprflflfffprflfflfffpllfrfplfplfrfrfP"
sol1 = "fplfrfffrffffrffprflflfffprflflfffprflflfplfffrfffrffflfflflfplfrfrffprflflfffprflflfplffffrffflffflflfffplfrfrffprflflffffprrffffrfflffflfflflfplfrfrfffplfrfrffprflflfffprflfflfffpllfrfplfplfrfrfP"
some_sol = "fffrflflfprrfllfffprflfrffrfrfffplffrfffrffflflffprflflffffprflflffprflfflfplfffP"

path = Path(some_sol, get_default_state_machines())
setup.run(path)
