#!/usr/bin/python3
import setup
from stateMachines import Path, get_default_state_machines

sol = "fplfrfffrffffrffprflflffffprrfffrffflfflflfplfrfrffprflflfffprflflfffprflflfplfffrffffrffflffflflfffplfrfrffprflflfffprflflfplfffrfflfffflfflflfplfrfrfffplfrfrffprflflfffprflfflfffpllfrfplfplfrfrfP"
sol1 = "fplfrfffrffffrffprflflfffprflflfffprflflfplfffrfffrffflfflflfplfrfrffprflflfffprflflfplffffrffflffflflfffplfrfrffprflflffffprrffffrfflffflfflflfplfrfrfffplfrfrffprflflfffprflfflfffpllfrfplfplfrfrfP"

path = Path(sol1, get_default_state_machines())
setup.run(path)
